### ISSUE TITLE
[meta] Improve UX

### ISSUE THREAD

**Issue by rgaiacs** [rgaiacs/ComicReader#7]
- [ ] Allow zoom in/out
- [ ] Use click on border to change pages
- [ ] Use slice to change pages
